- more clever python detection
git-svn-id: http://svn.code.sf.net/p/potassco/code/trunk/benchmark-tool@8895 c2a30a28-f9ed-4af8-86dc-e4e425da2d4f

diff --git a/bgen b/bgen
--- a/bgen
+++ b/bgen
@@ -1,6 +1,15 @@
 #!/bin/bash
-PYTHON=$(which python3)
-if [ ! -x $PYTHON ]; then
-	PYTHON=$(which python)
-fi
-PYTHONPATH="src" $PYTHON src/bgen.py "$@"
+
+function check_python() {
+	PYTHON=$1
+	shift
+	if [ -x "$PYTHON" ] && echo "import lxml" | "$PYTHON" &> /dev/null; then
+		PYTHONPATH="src" exec "$PYTHON" src/bgen.py "$@"
+	fi
+}
+
+check_python "$(which python)" "$@"
+check_python "$(which python3)" "$@"
+
+echo "error: no python interpreter with lxml module found"
+exit 1
